### ISSUE TITLE
vlei-verifier service crash after successful singlesig-single-user workflow run during clear authorization on valid presentation

### ISSUE THREAD

**Issue by ronakseth96** [GLEIF-IT/vlei-verifier#66]
After recent updates were pushed #63 and #65 to the vlei-verifier service, the entire credential issuance and verification workflow runs successfully, including report generation, API test, verification test. However, after about 15 minutes of idle time post-successful workflow execution, the verifier service crashes while processing clear authorization on a valid presentation.

The traceback from the crash:

```
keri: Headers/Body: Hict([('Host', 'vlei-verifier:7676'), ('User-Agent', 'Wget'), ('Accept', '*/*'), ('Connection', 'close')]) -- bytearray(b'')
2024-10-24 10:51:09 Traceback (most recent call last):
2024-10-24 10:51:09   File "/keripy/venv/bin/verifier", line 8, in <module>
2024-10-24 10:51:09     sys.exit(main())
2024-10-24 10:51:09              ^^^^^^
2024-10-24 10:51:09   File "/usr/local/var/vlei-verifier/src/verifier/app/cli/verifier.py", line 33, in main
2024-10-24 10:51:09     raise ex
2024-10-24 10:51:09   File "/usr/local/var/vlei-verifier/src/verifier/app/cli/verifier.py", line 28, in main
2024-10-24 10:51:09     directing.runController(doers=doers, expire=0.0)
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/keri/app/directing.py", line 665, in runController
2024-10-24 10:51:09     doist.do(doers=doers)
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 156, in do
2024-10-24 10:51:09     self.recur()  # increments .tyme runs recur context
2024-10-24 10:51:09     ^^^^^^^^^^^^
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 275, in recur
2024-10-24 10:51:09     tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
2024-10-24 10:51:09            ^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 568, in do
2024-10-24 10:51:09     self.done = self.recur(tyme=tyme)
2024-10-24 10:51:09                 ^^^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/usr/local/var/vlei-verifier/src/verifier/core/authorizing.py", line 323, in recur
2024-10-24 10:51:09     self.authn.processEscrows()
2024-10-24 10:51:09   File "/usr/local/var/vlei-verifier/src/verifier/core/authorizing.py", line 305, in processEscrows
2024-10-24 10:51:09     self.processPresentations()
2024-10-24 10:51:09   File "/usr/local/var/vlei-verifier/src/verifier/core/authorizing.py", line 127, in processPresentations
2024-10-24 10:51:09     for (aid,), state in self.vdb.iss.getItemIter():
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/keri/db/koming.py", line 154, in getItemIter
2024-10-24 10:51:09     yield (self._tokeys(key), self.deserializer(val))
2024-10-24 10:51:09                               ^^^^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/keripy/venv/lib/python3.12/site-packages/keri/db/koming.py", line 206, in __deserializeJSON
2024-10-24 10:51:09     val = helping.datify(self.schema, json.loads(bytes(val).decode("utf-8")))
2024-10-24 10:51:09                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
2024-10-24 10:51:09     return _default_decoder.decode(s)
2024-10-24 10:51:09            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
2024-10-24 10:51:09     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-10-24 10:51:09                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-24 10:51:09   File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-10-24 10:51:09     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-10-24 10:51:09 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-24 10:51:09 vLEI Verification Service running and listening on: 7676
2024-10-24 10:51:09 EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps account cleared after successful presentation
2024-10-24 10:51:09 Credential ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe presented for EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps is cryptographically valid.
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps, Credential pending authorization
2024-10-24 10:51:09 Cred filter status True, Successful authentication, storing user EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps with LEI 875500ELOZEL05BVXV37
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe, Credential pending authorization
2024-10-24 10:51:09 Cred filter status True, Successful authentication, storing user EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps with LEI 875500ELOZEL05BVXV37
2024-10-24 10:51:09 EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps account cleared after successful presentation
2024-10-24 10:51:09 Credential ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe presented for EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps is cryptographically valid.
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps, Credential pending authorization
2024-10-24 10:51:09 Cred filter status True, Successful authentication, storing user EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps with LEI 875500ELOZEL05BVXV37
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe, Credential pending authorization
2024-10-24 10:51:09 Cred filter status True, Successful authentication, storing user EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps with LEI 875500ELOZEL05BVXV37
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for EAswTp4Tyy4xqqrwZ1HpIAWPLevNnPmDneInNI98a-Ps, has expired: 0:10:00.028677 greater than 600
2024-10-24 10:51:09 ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe for ECNxQWbIR-_R1qtOE-c-pBHipTIU4YTqlClALWQwqsOe, has expired: 0:10:00.032706 greater than 600
```

**Comment by aydarng** [comment]
@2byrds This one is resolved and can be closed
