### ISSUE TITLE
KERI_BASER_MAP_SIZE fix

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/vlei-verifier#89]
A user can run into:
`\x00\x00\x00\x00\x00\x01\x00\x18\x00@\xa0\x15\xb7\x99O\xdb\x01@\xa0\x15\xb7\x99O\xdb\x01@\xa0\x15\xb7\x99O\xdb\x01PK\x05\x06\x00\x00\x00\x00\x02\x00\x02\x006\x01\x00\x001\x90\x0f\x00\x00\x00\r\n----------------------------148155701938411803778131--\r\n')
Traceback (most recent call last):
  File "/usr/local/var/vlei-verifier/src/verifier/core/reporting.py", line 327, in on_post
    self.filer.create(aid=aid, dig=dig, filename=part.secure_filename, typ=part.content_type,
  File "/usr/local/var/vlei-verifier/src/verifier/core/reporting.py", line 124, in create
    self.vdb.setVal(db=self.vdb.imgs, key=key, val=chunk)
  File "/keripy/src/keri/db/dbing.py", line 497, in setVal
    return (txn.put(key, val))
            ^^^^^^^^^^^^^^^^^
lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached`

See relevant keripy issues/PRs that add the KERI_BASER_MAP_SIZE env
https://github.com/WebOfTrust/keripy/issues/287.
https://github.com/WebOfTrust/keripy/pull/810 you can try setting the KERI_BASER_MAP_SIZE to a value bigger than 104857600, which is 100MB.
 
The code for the  KERI_BASER_MAP_SIZE has been in keripy (which the verifier uses) for 6 months so the feature/env variable should be available to the verifier. https://github.com/WebOfTrust/keripy/blame/f0643e2c7b80cd0194de881ff9c7fc7530eadb18/src/keri/db/basing.py#L598
 
according to the issue we should be able to increase the parameter all the way to a terabyte on a 64-bit system. 
 
Also, since the verifier db only needs to retain information long enough to provide a determination, we could clean up the filesystem occasionally. That would require shutting the verifier down, removing the files under /usr/local/var/keri/ but recommend listing everything under /usr/local/var/keri on the ticket first and being selective on what might need to be cleaned up.

**Comment by 2byrds** [comment]
Solved with latest release
